kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auth-service-monitoring
  namespace: auth-provider # TODO:HARDCODED
subjects:
  - kind: ServiceAccount
    name: auth-service
    namespace: auth-provider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
