apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../default
images:
  - name: quay.io/opendatahub/odh-notebook-controller
    ## FIXME: Temporary until PR is merged upstream
    newName: quay.io/maistra-dev/odh-notebook-controller
    newTag: enable_ossm
