apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  version: v2.3
  proxy:
    injection:
      autoInject: true
    runtime:
      container:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 129Mi
  tracing:
    type: Jaeger
    sampling: 10000
  addons:
    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
      name: kiali
  gateways:
    # no need to use IOR -
    # To be deprecated and we create the route manually
    openshiftRoute:
      enabled: false
    ingress:
      volumes:
        - volume:
            secret:
              secretName: istio-odh-oauth2
              optional: true
          volumeMount:
            name: odh-oauth2-tokens
            mountPath: "/etc/istio/odh-oauth2"
            readOnly: true
  techPreview:
    meshConfig:
      extensionProviders:
      - name: odh-auth-provider
        envoyExtAuthzGrpc:
          service: authorino-authorino-authorization.auth-provider.svc.cluster.local
          port: 50051
