apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: init-job-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - pods/log
      - pods/exec
      - secrets
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - list
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - get
  - apiGroups: 
      - config.openshift.io
    resources:
      - ingresses
    verbs:
      - get
  - apiGroups:
      - networking.istio.io
    resources:
      - envoyfilters
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - security.istio.io
    resources:
      - authorizationpolicies
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - oauth.openshift.io 
    resources:
      - oauthclients
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - patch
  - apiGroups:
      - maistra.io
    resources: 
      - servicemeshcontrolplanes
    verbs:
      - get
      - watch
      - list