apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: init-job-pod-operations
rules:
  - apiGroups:
      - ""
    resources:
      - pods/log
      - pods/exec
    verbs:
      - get
      - list
      - create
      - delete
