apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: init-job-read
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
  - apiGroups: 
      - config.openshift.io
    resources:
      - ingresses
    verbs:
      - get
  - apiGroups:
      - networking.istio.io
    resources:
      - envoyfilters
    verbs:
      - get
  - apiGroups:
      - security.istio.io
    resources:
      - authorizationpolicies
    verbs:
      - get
  - apiGroups:
      - oauth.openshift.io 
    resources:
      - oauthclients
    verbs:
      - create
      - get
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - patch
  - apiGroups:
      - maistra.io
    resources: 
      - servicemeshcontrolplanes
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - maistra.io
    resources: 
      - servicemeshmembers
    verbs:
      - get
