apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
  namespace: $AUTH_NS
spec:
  image: quay.io/kuadrant/authorino:v0.12.0
  authConfigLabelSelectors: authorino/topic=odh
  clusterWide: true
  listener:
    tls:
      enabled: false
  oidcServer:
    tls:
      enabled: false