apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../rbac
- smm.yaml
- operator-cluster-wide-no-tls.yaml
- namespace.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: odh-auth

configMapGenerator:
- name: authorino-config
  env: params.env

generatorOptions:
  disableNameSuffixHash: true

vars:
- name: istioNamespace
  objref:
    kind: ConfigMap
    name: authorino-config
    apiVersion: v1
  fieldref:
    fieldpath: data.istioNamespace
- name: smcpName
  objref:
    kind: ConfigMap
    name: authorino-config
    apiVersion: v1
  fieldref:
    fieldpath: data.smcpName

configurations:
- params.yaml