apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: ${SMCP_NAME}
  namespace: ${ISTIO_NAMESPACE}
spec:
  techPreview:
    meshConfig:
      extensionProviders:
      - name: odh-auth-provider
        envoyExtAuthzGrpc:
          service: authorino-authorino-authorization.auth-provider.svc.cluster.local
          port: 50051
