apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: ${SMCP_NAME}
  namespace: ${ISTIO_NAMESPACE}
spec:
  proxy:
    injection:
      autoInject: true
  gateways:
    ingress:
      volumes:
        - volume:
            secret:
              secretName: istio-odh-oauth2
              optional: true
          volumeMount:
            name: odh-oauth2-tokens
            mountPath: "/etc/istio/odh-oauth2"
            readOnly: true

