apiVersion: authorino.kuadrant.io/v1beta1
kind: AuthConfig
metadata:
  name: odh-dashboard-protection
  labels:
    authorino/topic: odh
spec:
  hosts:
  - "opendatahub.$DOMAIN"
  identity:
  - name: kubernetes-users
    kubernetes:
      audiences: 
      - "https://kubernetes.default.svc"
  authorization:
  - name: k8s-rbac-only-service-viewers
    kubernetes:
      user:
        valueFrom: { authJSON: auth.identity.username }
      resourceAttributes:
        namespace:
          value: $ODH_NAMESPACE
        group:
          value: ""
        resource:
          value: services
        name:
          value: odh-dashboard
        verb:
          value: get
  response:
  - name: x-auth-data
    json:
      properties:
      - name: username
        valueFrom: { authJSON: auth.identity.username }
  denyWith:
    unauthenticated:      
      message:
        value: "Access denied"
    unauthorized:
      message:
        value: "Unauthorized"

