apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- jupyter-minimal-notebook-imagestream.yaml
- jupyter-datascience-notebook-imagestream.yaml
- jupyter-minimal-gpu-notebook-imagestream.yaml
- jupyter-pytorch-notebook-imagestream.yaml
- jupyter-tensorflow-notebook-imagestream.yaml
- jupyter-trustyai-notebook-imagestream.yaml
commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: notebooks


