apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- operatorgroup.yaml
namespace: opendatahub
commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: odh-common
  app.kubernetes.io/part-of: odh-common

configMapGenerator:
- name: odh-common-config
  env: params.env
- name: service-mesh-refs
  literals:
    - MESH_NAMESPACE=$(istioNamespace)
    - CONTROL_PLANE_NAME=$(smcpName)
  
generatorOptions:
  disableNameSuffixHash: true

vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: odh-common-config
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
- name: istioNamespace
  objref:
    kind: ConfigMap
    name: odh-common-config
    apiVersion: v1
  fieldref:
    fieldpath: data.istioNamespace
- name: smcpName
  objref:
    kind: ConfigMap
    name: odh-common-config
    apiVersion: v1
  fieldref:
    fieldpath: data.smcpName

configurations:
- params.yaml
