varReference:
- path: spec/targetNamespaces
  kind: OperatorGroup
  apiGroup: operators.coreos.com
- path: spec/controlPlaneRef/name
  kind: ServiceMeshMember
  apiGroup: maistra.io/v1
- path: spec/controlPlaneRef/namespace
  kind: ServiceMeshMember
  apiGroup: maistra.io/v1
