apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

configMapGenerator:
  - name: config
    behavior: replace
    literals:
      - USE_ISTIO=true
      - ISTIO_GATEWAY=opendatahub/odh-gateway # TODO set by the ossm plugin
